# Generated by Django 3.0.3 on 2020-04-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='hero_headshots/')),
            ],
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
