# Generated by Django 3.0.3 on 2020-04-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200415_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='headshot',
            new_name='image',
        ),
    ]
